main = "src/index.js"
name = "csp-intake"
compatibility_date = "2024-09-14"
account_id = "ACCOUNT_ID" # Ensure this is the correct ID for your account

[[d1_databases]]
binding = "CSP_REPORTS" # This should match what you're using in the Worker script (env.CSP_REPORTS)
database_name = "csp-tool"
database_id = "DATABASE_ID" # Ensure this is the correct ID for your D1 database

[placement]
mode = "smart"

[observability]
enabled = true

# Explicitly disable workers.dev
workers_dev = false

# Route list should match Reporter worker

[[routes]]
pattern = "example.com/csp"
zone_id = "ZONE_ID" # Ensure this is the correct ID for your CSP Zone

[[routes]]
pattern = "example.com/csp"
zone_id = "ZONE_ID" # Ensure this is the correct ID for your CSP Zone